# Progetto

## Importo pacchetti & dataset

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn.model_selection as model_select
import sklearn.preprocessing as prep

from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from collections import Counter
from sklearn.cluster import DBSCAN
from sklearn.cluster import KMeans
from imblearn.over_sampling import SMOTE
from sklearn.svm import SVC
from sklearn.preprocessing import RobustScaler

In [2]:
dataset = pd.read_csv('training_set.csv')
dataset

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F12,F13,F14,F15,F16,F17,F18,F19,F20,CLASS
0,-0.555694,-0.848258,0.132180,-4.061760,1.661394,2.219988,0.360537,2.537116,-0.613588,2.078144,...,-2.492234,0.808907,-1.078887,3.438161,2.372122,1.899934,2.372122,2.219416,0.132180,2
1,0.293193,-2.628978,-1.154407,0.538828,-0.169857,3.487574,0.443397,-0.006410,-0.125778,1.223669,...,-1.723842,1.772836,0.467387,-1.501851,-3.599221,-0.968531,-3.599221,1.127776,-1.154407,0
2,-2.078656,-0.834492,1.241461,1.010122,-1.638526,0.247378,-1.887390,-1.331368,-2.159086,0.002788,...,-1.686278,-1.047410,-1.133299,-1.953928,-1.149684,1.111692,-1.149684,0.134184,1.241461,1
3,-1.294256,-2.804065,-1.335397,-1.351379,-0.327137,1.199219,0.262458,0.825120,-0.638883,1.660732,...,4.437570,-0.093413,2.637345,-2.415704,-4.679002,0.511314,-4.679002,0.805571,-1.335397,0
4,-0.525611,0.024948,1.609361,-0.248425,1.533188,0.580862,0.049771,-0.430270,-0.714264,-0.186867,...,0.404803,-0.733368,1.288384,-1.646543,-1.020989,0.658584,-1.020989,1.412792,1.609361,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,0.405098,0.592920,2.441859,-1.134919,2.248627,2.509097,-0.227617,0.275321,-0.274926,-0.595862,...,-0.169544,-0.255823,2.695956,-2.220396,-2.432903,-0.131110,-2.432903,-0.479939,2.441859,1
7996,-0.404388,1.813804,-2.483380,2.093664,0.139423,2.617027,0.489677,1.387914,-0.363073,0.030530,...,0.124103,0.056482,-0.333988,-1.204211,-0.224673,1.521622,-0.224673,-1.096852,-2.483380,2
7997,0.233546,-1.003142,-2.121826,1.581558,1.152723,-0.987152,0.337969,-4.654229,-0.417682,-1.260857,...,2.469214,2.782867,0.888288,0.335607,-2.248307,-1.386542,-2.248307,0.934043,-2.121826,0
7998,1.120382,0.194409,-0.672968,0.005154,2.290353,4.112554,0.720367,0.563533,-1.009534,-1.551473,...,0.607569,3.102179,4.237942,-0.710731,-0.359420,-1.500903,-0.359420,-0.658633,-0.672968,1
7999,0.994641,-1.185386,-3.610239,0.185566,-1.534623,3.021333,-0.721372,-3.250708,-0.034000,-0.102102,...,-3.273256,3.908861,0.809098,2.970013,-2.104526,-0.419366,-2.104526,1.655029,-3.610239,3

## Manipolazione Dataset

In [3]:
dataset.describe()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F12,F13,F14,F15,F16,F17,F18,F19,F20,CLASS
count,7994.000000,7994.000000,7999.000000,7999.000000,7996.000000,7994.000000,7996.000000,7991.000000,7994.000000,7994.000000,...,7994.000000,7997.000000,7990.000000,7998.000000,7994.000000,7996.000000,7993.000000,7995.000000,7997.000000,8000.000000
mean,-0.013077,-0.261413,-0.356239,-0.107298,-0.505798,0.170845,-0.142636,0.135534,-0.004581,0.017338,...,0.000023,-0.051170,-0.011521,0.032990,-0.294768,-0.026807,-0.293875,0.001092,-0.355555,1.463375
std,1.006235,1.852793,1.794600,3.038362,1.818965,3.802454,1.901893,1.846124,1.005507,1.005563,...,1.960223,1.936503,2.069112,2.013245,1.970592,0.978187,1.971526,0.996603,1.794666,1.231198
min,-4.181155,-6.980290,-7.563245,-13.133565,-9.011808,-15.887455,-7.934826,-8.608330,-3.472781,-3.697495,...,-7.212589,-8.133189,-7.823196,-8.969136,-7.037129,-3.621038,-7.037129,-4.013615,-7.563245,0.000000
25%,-0.698506,-1.441144,-1.564076,-1.854212,-1.735180,-2.187097,-1.412976,-1.099665,-0.684807,-0.672081,...,-1.325372,-1.337362,-1.383780,-1.298123,-1.612006,-0.689233,-1.612119,-0.669021,-1.563262,0.000000
50%,-0.028194,-0.261095,-0.375098,-0.022912,-0.511772,0.086112,-0.117316,0.144827,0.004093,0.029326,...,-0.037385,-0.067058,-0.036499,-0.033036,-0.308933,-0.035249,-0.308409,-0.004635,-0.373514,2.000000
75%,0.666096,0.944857,0.824168,1.757135,0.691109,2.445748,1.121002,1.411072,0.664729,0.704140,...,1.283942,1.245172,1.365177,1.314362,1.021518,0.634916,1.022557,0.676510,0.825741,3.000000
max,3.774161,7.155359,6.774458,10.975842,6.420768,17.343261,7.222491,6.664533,3.811616,3.391975,...,7.181241,8.819808,7.970802,9.235606,9.415568,3.951352,9.415568,3.606960,6.774458,3.000000

In [4]:
# Separate features and target labels.
target = 'CLASS'
x = dataset.drop(target, axis=1)
print('Variabili Indipendenti X:', x)

Variabili Indipendenti X:             F1        F2        F3        F4        F5        F6        F7  \
0    -0.555694 -0.848258  0.132180 -4.061760  1.661394  2.219988  0.360537
1     0.293193 -2.628978 -1.154407  0.538828 -0.169857  3.487574  0.443397
2    -2.078656 -0.834492  1.241461  1.010122 -1.638526  0.247378 -1.887390
3    -1.294256 -2.804065 -1.335397 -1.351379 -0.327137  1.199219  0.262458
4    -0.525611  0.024948  1.609361 -0.248425  1.533188  0.580862  0.049771
...        ...       ...       ...       ...       ...       ...       ...
7995  0.405098  0.592920  2.441859 -1.134919  2.248627  2.509097 -0.227617
7996 -0.404388  1.813804 -2.483380  2.093664  0.139423  2.617027  0.489677
7997  0.233546 -1.003142 -2.121826  1.581558  1.152723 -0.987152  0.337969
7998  1.120382  0.194409 -0.672968  0.005154  2.290353  4.112554  0.720367
7999  0.994641 -1.185386 -3.610239  0.185566 -1.534623  3.021333 -0.721372

            F8        F9       F10       F11       F12       F13       F14  \
0     2.537116 -0.613588  2.078144  0.128270 -2.492234  0.808907 -1.078887
1    -0.006410 -0.125778  1.223669  0.239508 -1.723842  1.772836  0.467387
2    -1.331368 -2.159086  0.002788 -0.397360 -1.686278 -1.047410 -1.133299
3     0.825120 -0.638883  1.660732 -2.045188  4.437570 -0.093413  2.637345
4    -0.430270 -0.714264 -0.186867  0.572004  0.404803 -0.733368  1.288384
...        ...       ...       ...       ...       ...       ...       ...
7995  0.275321 -0.274926 -0.595862  1.379110 -0.169544 -0.255823  2.695956
7996  1.387914 -0.363073  0.030530  0.962490  0.124103  0.056482 -0.333988
7997 -4.654229 -0.417682 -1.260857  4.472366  2.469214  2.782867  0.888288
7998  0.563533 -1.009534 -1.551473 -0.697174  0.607569  3.102179  4.237942
7999 -3.250708 -0.034000 -0.102102  6.857379 -3.273256  3.908861  0.809098

           F15       F16       F17       F18       F19       F20
0     3.438161  2.372122  1.899934  2.372122  2.219416  0.132180
1    -1.501851 -3.599221 -0.968531 -3.599221  1.127776 -1.154407
2    -1.953928 -1.149684  1.111692 -1.149684  0.134184  1.241461
3    -2.415704 -4.679002  0.511314 -4.679002  0.805571 -1.335397
4    -1.646543 -1.020989  0.658584 -1.020989  1.412792  1.609361
...        ...       ...       ...       ...       ...       ...
7995 -2.220396 -2.432903 -0.131110 -2.432903 -0.479939  2.441859
7996 -1.204211 -0.224673  1.521622 -0.224673 -1.096852 -2.483380
7997  0.335607 -2.248307 -1.386542 -2.248307  0.934043 -2.121826
7998 -0.710731 -0.359420 -1.500903 -0.359420 -0.658633 -0.672968
7999  2.970013 -2.104526 -0.419366 -2.104526  1.655029 -3.610239

[8000 rows x 20 columns]

In [5]:
y = dataset[[target]]
print('\nVariabili Dipendenti Y:', y)

Variabili Dipendenti Y:       CLASS
0         2
1         0
2         1
3         0
4         1
...     ...
7995      1
7996      2
7997      0
7998      1
7999      3

[8000 rows x 1 columns]

In [6]:
features_list = x.columns.values.tolist()
print('\nLista Features:', features_list)

Lista Features: ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20']

In [7]:
# Split dataset in training set and test set.
train_x, test_x, train_y, test_y = \
        model_select.train_test_split(x, y,
                                      test_size=0.2,
                                      random_state=42,
                                      stratify=y)
print('\nTraining set shape:', train_x.shape, train_y.shape)
print('Test set shape:', test_x.shape, test_y.shape)

Training set shape: (6400, 20) (6400, 1)
Test set shape: (1600, 20) (1600, 1)

## Trattamento Outliers & NaN

In [8]:
# funzione che conta il numero di valori mancanti per ogni attributo
def get_na_count(dataset):
    # per ogni elemento (i,j) del dataset, isna() restituisce 
    # TRUE/FALSE se il valore corrispondente è mancante/presente
    boolean_mask = dataset.isna()
    # contiamo il numero di TRUE per ogni attributo sul dataset
    return boolean_mask.sum(axis=0)

In [9]:
# calcoliamo il numero di valori mancanti su train e test
summary_train = get_na_count(train_x)
print(summary_train)
summary_test = get_na_count(test_x)
print(summary_test)

F1     5
F2     6
F3     0
F4     0
F5     2
F6     5
F7     3
F8     7
F9     5
F10    6
F11    3
F12    5
F13    2
F14    9
F15    2
F16    4
F17    2
F18    5
F19    4
F20    2
dtype: int64
F1     1
F2     0
F3     1
F4     1
F5     2
F6     1
F7     1
F8     2
F9     1
F10    0
F11    2
F12    1
F13    1
F14    1
F15    0
F16    2
F17    2
F18    2
F19    1
F20    1
dtype: int64

In [10]:
imputer = KNNImputer(n_neighbors=2)
z = imputer.fit_transform(x)

In [13]:
class DBScanner(DBSCAN):
        outliers = None
        def __init__(self,eps=0.1,min_samples=5):
            super().__init__(eps=eps,min_samples=min_samples)
            #self.Scanner = DBSCAN(eps=eps,min_samples=min_samples)
            
        def fit(self,x,y=None):
            x = pd.DataFrame(x)
            model = super().fit(x)
            outliers = x[model.labels_==-1].index.values
        
        def transform(self,x,y=None):
            x = pd.DataFrame(x).drop(index = outliers)
            return x

In [14]:
scanner = DBScanner(eps = 10,min_samples = 100)
scanner.fit(z)
z1 = scanner.transform(z)

NameError: name 'outliers' is not defined

In [ ]:
z1

In [ ]:
z3 = pd.DataFrame(z)
z3

In [26]:
model = DBSCAN(eps=10, min_samples=100).fit(z)
print(model)

DBSCAN(eps=10, min_samples=100)

In [27]:
outliers = pd.DataFrame(z)

print(Counter(model.labels_))
a = outliers[model.labels_ == -1].index.values
a

Counter({0: 7997, -1: 3})

array([4400, 6113, 7730], dtype=int64)

In [28]:
model.labels_[model.labels_ == -1] .size

3

In [ ]:
b = a.index.values
b

In [ ]:
kmeans = KMeans(n_clusters=4, random_state=42).fit(z)
kmeans.labels_

In [ ]:
a = kmeans.labels_[kmeans.labels_ == 0] .size
b = kmeans.labels_[kmeans.labels_ == 1] .size
c = kmeans.labels_[kmeans.labels_ == 2] .size
d = kmeans.labels_[kmeans.labels_ == 3] .size
print('numero cluster 0:',a)
print('numero cluster 1:',b)
print('numero cluster 2:',c)
print('numero cluster 3:',d)

In [ ]:
a+b+c+d

In [ ]:
# In teoria dovrei togliere gli outliers multi variati ovvero quelli trovati con DBSCAN ma non so come adesso...

In [ ]:
# Dovrei trovare gli outliers univariati

In [ ]:
#Bisogna fare il balancing

In [ ]:
oversample = SMOTE()
z, y = oversample.fit_resample(z, y)
print(z.size)
print(y.size)

In [ ]:
transformer = RobustScaler().fit(z)
transformer.transform(z)

In [ ]:
#Devo usare 
QDA()

In [ ]:
def show_boxplot_features(dataset, title):
    """Displays features boxplot."""
    sns.boxplot(data=dataset).set(title=title)
    plt.show()

In [ ]:
title = 'Training set whit Outliers and Nan value'
show_boxplot_features(z, title)

In [18]:
class KNNReplacerIQR(KNNImputer):
    #Crea la classe di KNNReplace per utilizzarlo in pipeline

    def __init__(self, n_neighbors=5):
        super().__init__(n_neighbors=n_neighbors)
        self.lower_bound = None
        self.upper_bound = None
        self.imputer = KNNImputer(n_neighbors=n_neighbors)

    def fit(self, x, y=None):
        #Calcola l'IRQ e fittalo sui dati
        x = pd.DataFrame(x)
        q1 = x.quantile(0.25)
        q3 = x.quantile(0.75)
        iqr = q3 - q1
        self.lower_bound = q1 - (1.5 * iqr)
        self.upper_bound = q3 + (1.5 * iqr)
        self.imputer.fit(
            x.where(~((x < self.lower_bound) | (x > self.upper_bound)), np.nan)
        )
        return self

    def transform(self, x, y=None):
        #Trova gli outliers e rimpiazzali
        x = pd.DataFrame(x)
        x.where(~((x < self.lower_bound) | (x > self.upper_bound)),
                np.nan,
                inplace=True)
        return self.imputer.transform(x)